---
- hosts: all
  tasks:
    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest
    - name: Update repositories cache and install "foo" package
      apt:
        update_cache: yes
