- name:  Instalar "OCS-Inventory"
  hosts: all
  tasks:   
    - name: copiar archivo .exe
      win_copy:
        src: /var/lib/awx/instalacion/programas_windows
        dest: C:\
        
    - name: Instalar
      win_package:
        user_name: PITMA\daniel.santivanez
        user_password: 
        path: C:\programas_windows\OCS-NG-Windows-Agent-Setup.exe
        creates_path: C:\Program Files (x86)\OCS-NG-Windows-Agent-Setup.exe
        creates_version: 2.1.1.3
        state: present
        arguments:
        - /S
        - /SERVER=http://ocs.netkia.es/ocsinventory
        - /NET
        - /NOW
        - /reboot
    
    - name: Reiniciar equipo
      win_reboot:
        reboot_timeout: 120
