- name:  Instalar "OCS-Inventory"
  hosts: all
  tasks:   
  
    - name: Instalar
      win_package:
        user_name: PITMA\daniel.santivanez
        user_password: ReitterVonDieEinsamkeit18
        path: C:\programas_windows\OCS-NG-Windows-Agent-Setup.exe
        creates_path: C:\Program Files (x86)\OCS-NG-Windows-Agent-Setup.exe
        creates_version: 2.1.1.3
        state: present
        arguments:
        - /S
        - /SERVER=http://ocs.netkia.es/ocsinventory
        - /NET
        - /NOW
        - /restart

