- name:  Intalación de Programas Básicos
  hosts: all
  tasks:

    - name: Crear directorio para alojar los ejecutables
      win_file:
        path: C:\AWX
        state: directory

    - name: copiar archivos .exe de servidor a equipo
      win_copy:
        src: /var/lib/awx/instalacion/programas_windows/instalacion_basica
        dest: C:\AWX
 
    - name: instalar archivo OCS-inventory.exe
      win_package:
        path: C:\AWX\instalacion_basica\OCS-NG-Windows-Agent-Setup.exe
        creates_path: C:\Program Files (x86)\OCS-NG-Windows-Agent-Setup.exe
        creates_version: 2.1.1.3
        arguments: 
        - /S
        - /SERVER=http://ocs.netkia.es/ocsinventory
        - /TAG=NET
        - /norestart
        state: present
