- name:  Intalación de Programas Básicos
  hosts: all
  tasks:

    - name: Crear directorio para alojar los ejecutables
      win_file:
        path: C:\AWX
        state: directory

    - name: copiar archivos .exe de servidor a equipo
      win_copy:
        src: /var/lib/awx/instalacion/programas_windows/ScreenConnect
        dest: C:\AWX
    
    - name: Install Firefox
      win_chocolatey:
        name: firefoxesr
        state: present
    
    - name: instalar archivo .exe
      win_package:
        path: C:\AWX\ScreenConnect\ConnectWiseControl.ClientSetup.exe
        creates_path: C:\Program Files\ConnectWiseControl.ClientSetup.exe
        creates_version: 6.5.16479.6613
        arguments:  
          - /passive
          - /quiet
          - /qn
        state: present
