- name:  Intalación de Programas Básicos
  hosts: all
  tasks:

    - name: Crear directorio para alojar los ejecutables
      win_file:
        path: C:\AWX
        state: directory

    - name: copiar archivos .exe de servidor a equipo
      win_copy:
        src: /var/lib/awx/instalacion/programas_windows/ScreenConnect
        dest: C:\AWX
        
    - name: instalar archivo .exe
      win_msi:
        path: C:\AWX\ScreenConnect\ConnectWiseControl.ClientSetup.msi
        extra_args: 
          - /passive
          - /quiet
          - /qn
        state: present
