---
- hosts: all
  tasks:

    - name: leer contenido
      command: cat /etc/issue.net
      register: ansible

    - debug:
      with_items:
        - "{{ansible.stdout_lines}}"

    - shell: proftpd -V | grep Version
      register: pro

    - debug:
      with_items:
        - "{{pro.stdout_lines}}"
