---
- hosts: all
  tasks:

    - name: Leer nombre del host
      command: cat /etc/hostname
      register: ansible

    - debug:
      with_items:
        - "{{ansible.stdout_lines}}"

    - name: Leer versión del host
      command: cat /etc/issue.net
      register: awx

    - debug:
      with_items:
        - "{{awx.stdout_lines}}"

    - shell: proftpd -V | grep Version
      register: pro
      ignore_errors: yes

    - debug:
      with_items:
        - "{{pro.stdout_lines}}"

    - blockinfile: create=yes dest=/root/debian.txt  block="{{awx.stdout_lines}},{{ansible.stdout_lines}},{{pro.stdout_lines}}"  state=present marker=""

    - shell: cat /root/debian.txt
      register: debian

    - fetch: src=/root/debian.txt dest=/var/local/hosts/

- hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:

    - script: /var/local/script.sh
