- name:  Intalación de Programas Básicos
  hosts: all
  tasks:
        
    - name: Copiar archivos .exe de servidor a equipo
      win_copy:
        src: /var/lib/awx/instalacion/programas_windows/soporte
        dest: C:\AWX
        
    - name: Instalar Sophos.exe
      win_shell: C:\AWX\soporte\SophosSetup.exe
