- name:  Intalación de Programas de Soporte
  hosts: all
  tasks:
    
    - name: Copiar archivos .exe de servidor a equipo
      win_copy:
        src: /var/lib/awx/instalacion/programas_windows/soporte
        dest: C:\AWX
  
    - name: instalación de ScreenConnect.exe
      win_command: C:\AWX\soporte\ScreenConnect.bat
