- name:  Intalación de Programas Básicos
  hosts: all
  tasks:

    - name: Crear directorio para alojar los ejecutables
      win_file:
        path: C:\AWX
        state: directory

    - name: copiar archivo .exe
      win_copy:
        src: /var/lib/awx/instalacion/programas_windows/instalacion_basica
        dest: C:\AWX\instalacion_basica
 
    - name: instalar archivo .exe
      win_package:
        path: C:\AWX\instalacion_basica\OCS-NG-Windows-Agent-Setup.exe
        creates_path: C:\Program Files (x86)\OCS-NG-Windows-Agent-Setup.exe
        creates_version: 2.1.1.3
        arguments: 
        - /S
        - /SERVER=http://ocs.netkia.es/ocsinventory
        - /NET
        - /norestart
        state: present

    - name: instalar archivo .exe
      win_package:
        path: C:\AWX\instalacion_basica\ccsetup542.exe
        creates_path: C:\Program Files (x86)\ccsetup542.exe
        arguments: 
        - /S
        - /norestart
        state: present

    - name: instalar archivo .exe
      win_package:
        path: C:\AWX\instalacion_basica\SophosSetup_Netkia.exe
        creates_path: C:\Program Files (x86)\SophosSetup_Netkia.exe
        arguments: 
        - /S
        - /norestart
        state: present

    - name: Crear directorio para alojar el certificado
      win_file:
        path: C:\Certificados
        state: directory

    - name: copiar archivo .exe
      win_copy:
        src: C:\AWX\instalacion_basica\Netkia_Desarrollo.p12
        dest: C:\Certificados
        remote_src: yes   

    - name: Reiniciar equipo
      win_reboot:
        reboot_timeout: 60
