- name:  Intalación de Programas Básicos
  hosts: all
  tasks:

    - name: Crear directorio para alojar los ejecutables
      win_file:
        path: C:\AWX
        state: directory

    - name: copiar archivos .exe de servidor a equipo
      win_copy:
        src: /var/lib/awx/instalacion/programas_windows/instalacion_basica
        dest: C:\AWX
 
    - name: instalar archivo OCS-inventory.exe
      win_package:
        path: C:\AWX\instalacion_basica\OCS-NG-Windows-Agent-Setup.exe
        creates_path: C:\Program Files (x86)\OCS-NG-Windows-Agent-Setup.exe
        creates_version: 2.1.1.3
        arguments: 
        - /S
        - /SERVER=http://ocs.netkia.es/ocsinventory
        - /NET
        - /norestart
        state: present

    - name: instalar archivo CCleaner.exe
      win_package:
        path: C:\AWX\instalacion_basica\ccsetup542.exe
        creates_path: C:\Program Files (x86)\ccsetup542.exe
        arguments: 
        - /S
        - /norestart
        - /REGISTRY
        state: present
    
    - name: Install Firefox
      win_chocolatey:
        name: firefoxesr
        state: present

    - name: Install Chrome
      win_chocolatey:
        name: googlechrome
        state: present

    - name: Install Thunderbird
      win_chocolatey:
        name: thunderbird
        state: present

    - name: Crear directorio para alojar el certificado
      win_file:
        path: C:\Certificados
        state: directory

    - name: copiar archivo .exe
      win_copy:
        src: C:\AWX\instalacion_basica\Netkia_Desarrollo.p12
        dest: C:\Certificados\Netkia_Desarrollo.p12
        remote_src: yes   

    - name: Reiniciar equipo
      win_reboot:
        reboot_timeout: 420
