- name:  Intalación de WinSshFs
  hosts: all
  tasks:
    - name: Crear directorio para alojar los ejecutables
      win_file:
        path: C:\AWX
        state: directory

    - name: Copiar archivos .exe de servidor a equipo
      win_copy:
        src: /var/lib/awx/instalacion/programas_windows/WinSshFs
        dest: C:\AWX
        
    - name: instalar archivo .exe
      win_package:
        path: C:\AWX\WinSshFs\DokanSetup.exe
        creates_path: C:\Program Files (x86)\DokanSetup.exe
        arguments:
        - /S
        state: present
      
    - name: Instalación de WinSshFs
      win_msi:
        path: C:\AWX\WinSshFs\WinSSHFS-1.6.1.13-devel.msi
